[workspace]
members = [
  "packages/adapter",
  "packages/cli",
  "packages/core",
  "packages/dynamic-html",
  "clouds/http-router",
  "clouds/views",
]

[workspace.dependencies]
densky-adapter = { path = "./packages/adapter/" }
