name: Build

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose --release
    
    - name: Save file
      run: mv target/release/densky densky
      
    - name: Remove unused
      run: |
        rm -r example_server
        rm -r packages
        rm -r target
        
    - name: Commit it
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "action: upload build"
        branch: build-${{ matrix.os }}

        push_options: '--force'
        create_branch: true
