name: Build

on: 
  workflow_dispatch:
    inputs:
      Linux:
        description: 'Build on Linux - Ubuntu'
        type: boolean
      Macos:
        description: 'Build on Macos'
        type: boolean
      Windows:
        description: 'Build on Windows'
        type: boolean

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
      
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            bin_name: densky-linux-x64
            bin_path: densky
            cloud_http: libcloud_http_router.so
            will_run: ${{ inputs.Linux }}
          - os: macos-latest
            bin_name: densky-macos-x64
            bin_path: densky
            cloud_http: libcloud_http_router.dylib
            will_run: ${{ inputs.Macos }}
          - os: windows-latest
            bin_name: densky-windows-x64.exe
            bin_path: densky.exe
            cloud_http: cloud_http_router.dll
            will_run: ${{ inputs.Windows }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      if: ${{ matrix.will_run }}
      with:
        submodules: true
        
    - name: Build CLI
      if: ${{ matrix.will_run }}
      run: cargo build --package densky --verbose --release
      
    - uses: actions/upload-artifact@v3
      if: ${{ matrix.will_run }}
      with:
        name: ${{ matrix.bin_name }}
        path: target/release/${{ matrix.bin_path }}
    
    - name: Build HTTP cloud
      if: ${{ matrix.will_run }}
      run: cargo build --package cloud-http-router --verbose --release
      
    - uses: actions/upload-artifact@v3
      if: ${{ matrix.will_run }}
      with:
        name: ${{ matrix.cloud_http }}
        path: target/release/${{ matrix.cloud_http }}

