name: Build

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  
    
    - name: Save file
      run: mv example_server/config.ts densky
      
    - name: Remove unused
      run: |
        rm -r example_server
        rm -r packages
        
    - name: Commit it
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "action: upload build"
        branch: build-ubuntu-latest

        push_options: '--force'
